//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gta_ovrd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gta_ovrd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///# Object types
        ///#
        ///IDE common:/data/default.ide
        ///IDE common:/data/vehicles.ide
        ///IDE common:/data/peds.ide
        ///
        ///ANIMGRP common:/data/animgrp.dat
        ///HANDLING common:/ovrd/handling.dat
        ///VEHICLEEXTRAS common:/data/VehicleExtras.dat
        ///PLAYER platform:/models/cdimages/playerped.rpf
        ///PEDGRP common:/data/pedgrp.dat
        ///CARGRP common:/data/cargrp.dat
        ///RADIO common:/data/radiohud.dat
        ///RADIOLOGOS independent:/textures/radio_hud.itd
        ///WEAPONINFO common:/data/weaponinfo.xml
        ///THROWNWEAPONINFO common:/data/thrownweaponinfo.xml        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string def {
            get {
                return ResourceManager.GetString("def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///# Load IDEs first, then the models and after that the IPLs
        ///#
        ///
        ///#IMG ASSETS.IMG
        ///IMG common/ovrd/overrd.IMG
        ///IMGLIST common:/data/images.txt
        ///
        ///#
        ///#  Water
        ///#
        ///WATER common:/DATA/WATER.DAT common:/DATA/WATERLOW.DAT
        ///
        ///
        ///
        ///#
        ///# Object types
        ///#
        ///
        ///IDE common:/DATA/gtxd.IDE
        ///
        ///#props files
        ///IDE platform:/DATA/MAPS/GENERIC/procobj.IDE
        ///IDE platform:/DATA/MAPS/PROPS/WINDOWS/GEN_WIN.IDE
        ///IDE platform:/DATA/MAPS/PROPS/STREET/ROOFTOP.IDE
        ///IDE platform:/DATA/MAPS/PROPS/STREET/amenitie.IDE
        ///IDE platform:/DATA/MAP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gta {
            get {
                return ResourceManager.GetString("gta", resourceCulture);
            }
        }
    }
}
